### PR TITLE
Add high quality files of afsy logo (AI, EPS, PDF)

### PR DESCRIPTION
**Pull request by cgrandval**
I needed high quality logo for making some goodies for AFSY and the PSD wasn't so good. So I created a new vectorized file (AI) for the hexagon version and export in EPS and PDF too.

### CODE REVIEW

**Comment by pimolo** [comment]
Hi @cgrandval, thanks a lot for this!

I will take a look at your files as soon as possible, so your PR can be merged before the end of the week.

**Comment by stof** [comment]
If you have a vectorized file, what about exporting it to SVG too ?

**Review by pimolo — APPROVED** [review]
An SVG file would be nice indeed.
In the logo with border, the spacing between the "a" of afsy and the left border is different from the one of the black logo.
But I think it's ok 😉

**Comment by Nek-** [comment]
This is cool. Will be better with an SVG. I add an issue for that.

**Pull request merged**
